Call function untitled() instead of isUntitled()
For OS_DARWIN platform, the call is incorrect: `TeXDocumentWindow.cpp:586:8: error: use of undeclared identifier 'isUntitled'`
In TexDocumentWindow.h, the function is called untitled() instead of isUntitled().
I changed it accordingly.

This fixes https://github.com/TeXworks/texworks/issues/885 after installing poppler with
`brew install CMake/packaging/mac/poppler.rb`